/* test_wormhole.cpp
Copyright (c) 2025 by test contributor

Endless Sky is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

Endless Sky is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include "es-test.hpp"

// Include only the tested class's header.
#include "../../../source/Wormhole.h"

// ... and any system includes needed for the test file.
#include <type_traits>

namespace { // test namespace

// #region mock data

// Insert file-local data here, e.g. classes, structs, or fixtures that will be useful
// to help test this class/method.

// #endregion mock data



// #region unit tests

// Test Class Traits
TEST_CASE( "Wormhole Class Traits", "[Wormhole]" ) {
	using T = Wormhole;
	SECTION( "Class Properties" ) {
		// Wormhole has member types that prevent it from being trivial.
		CHECK_FALSE( std::is_trivial_v<T> );
		CHECK( std::is_nothrow_destructible_v<T> );
		CHECK_FALSE( std::is_trivially_destructible_v<T> );
	}
	SECTION( "Construction Traits" ) {
		CHECK( std::is_default_constructible_v<T> );
		CHECK_FALSE( std::is_trivially_default_constructible_v<T> );
		CHECK( std::is_copy_constructible_v<T> );
		CHECK( std::is_move_constructible_v<T> );
	}
	SECTION( "Copy/Move Traits" ) {
		CHECK( std::is_copy_assignable_v<T> );
		CHECK( std::is_move_assignable_v<T> );
		CHECK_FALSE( std::is_trivially_copyable_v<T> );
	}
}

SCENARIO( "Creating a Wormhole with default constructor", "[Wormhole][Creation]" ) {
	GIVEN( "a default-constructed Wormhole" ) {
		Wormhole wormhole;

		WHEN( "checking initial state" ) {
			THEN( "it is not valid by default" ) {
				CHECK_FALSE( wormhole.IsValid() );
			}
			THEN( "it has no associated planet" ) {
				CHECK( wormhole.GetPlanet() == nullptr );
			}
			THEN( "it has default display name" ) {
				CHECK( wormhole.DisplayName() == "???" );
			}
			THEN( "it is not mappable by default" ) {
				CHECK_FALSE( wormhole.IsMappable() );
			}
			THEN( "it is not autogenerated by default" ) {
				CHECK_FALSE( wormhole.IsAutogenerated() );
			}
			THEN( "it has no links" ) {
				CHECK( wormhole.Links().empty() );
			}
		}
	}
}

SCENARIO( "Getting and setting planet association", "[Wormhole][Planet]" ) {
	GIVEN( "a default-constructed Wormhole" ) {
		Wormhole wormhole;
		REQUIRE( wormhole.GetPlanet() == nullptr );

		// Note: SetPlanet requires a valid Planet reference.
		// Testing with an actual Planet requires extensive GameData setup.
		// This test documents the expected behavior pattern.
	}
}

SCENARIO( "Wormhole validity checking", "[Wormhole][Validity]" ) {
	GIVEN( "a default-constructed Wormhole" ) {
		Wormhole wormhole;

		WHEN( "checking IsValid without any setup" ) {
			THEN( "it returns false because isDefined is false" ) {
				CHECK_FALSE( wormhole.IsValid() );
			}
		}

		// Note: Full IsValid testing requires:
		// 1. A valid Planet pointer (requires Planet to be properly loaded)
		// 2. Valid System pointers in the links map
		// These dependencies require GameData initialization and are better
		// suited for integration tests.
	}
}

SCENARIO( "Wormhole link operations", "[Wormhole][Links]" ) {
	GIVEN( "a default-constructed Wormhole with no links" ) {
		Wormhole wormhole;

		WHEN( "checking the links map" ) {
			THEN( "it is empty by default" ) {
				const auto &links = wormhole.Links();
				CHECK( links.empty() );
			}
		}

		// Note: WormholeSource and WormholeDestination require valid System references.
		// Creating System instances requires extensive GameData setup.
		// When no link exists for a system:
		// - WormholeSource(to) returns the first system whose destination is 'to'
		// - WormholeDestination(from) returns the destination for 'from' system
		// If no link matches, both return the input system.
		// These methods are better tested in integration tests.
	}
}

SCENARIO( "Wormhole display name", "[Wormhole][DisplayName]" ) {
	GIVEN( "a default-constructed Wormhole" ) {
		Wormhole wormhole;

		WHEN( "querying the display name" ) {
			THEN( "the default display name is '???'" ) {
				CHECK( wormhole.DisplayName() == "???" );
			}
		}

		// Note: Display name can be changed via Load() with a "display name" attribute.
		// Testing Load() requires GameData initialization.
	}
}

SCENARIO( "Wormhole mappable state", "[Wormhole][Mappable]" ) {
	GIVEN( "a default-constructed Wormhole" ) {
		Wormhole wormhole;

		WHEN( "checking if it is mappable" ) {
			THEN( "it is not mappable by default" ) {
				CHECK_FALSE( wormhole.IsMappable() );
			}
		}

		// Note: Mappable flag can be set via Load() with a "mappable" attribute,
		// or via LoadFromPlanet() based on whether the planet has a description.
	}
}

SCENARIO( "Wormhole autogenerated state", "[Wormhole][Autogenerated]" ) {
	GIVEN( "a default-constructed Wormhole" ) {
		Wormhole wormhole;

		WHEN( "checking if it is autogenerated" ) {
			THEN( "it is not autogenerated by default" ) {
				CHECK_FALSE( wormhole.IsAutogenerated() );
			}
		}

		// Note: IsAutogenerated() returns true when LoadFromPlanet() is called,
		// and false when Load() is called. This flag is used to determine if
		// the wormhole should be updated when game events modify the planet.
	}
}

SCENARIO( "Wormhole link color", "[Wormhole][Color]" ) {
	GIVEN( "a default-constructed Wormhole" ) {
		Wormhole wormhole;

		WHEN( "getting the link color" ) {
			THEN( "a color pointer is returned" ) {
				// Note: The default color is set from GameData::Colors().Get("map wormhole")
				// The ExclusiveItem<Color> always holds a valid Color object.
				const Color *color = wormhole.GetLinkColor();
				CHECK( color != nullptr );
			}
		}

		// Note: Link color can be customized via Load() with a "color" attribute,
		// specifying either a named color or RGB values.
	}
}

SCENARIO( "Copying and moving Wormhole instances", "[Wormhole][CopyMove]" ) {
	GIVEN( "two Wormhole instances" ) {
		Wormhole original;
		Wormhole copy;

		WHEN( "copy-assigning one to another" ) {
			copy = original;

			THEN( "both have the same state" ) {
				CHECK( copy.IsValid() == original.IsValid() );
				CHECK( copy.GetPlanet() == original.GetPlanet() );
				CHECK( copy.DisplayName() == original.DisplayName() );
				CHECK( copy.IsMappable() == original.IsMappable() );
				CHECK( copy.IsAutogenerated() == original.IsAutogenerated() );
			}
		}
	}

	GIVEN( "a Wormhole to move" ) {
		Wormhole original;
		Wormhole moved;

		WHEN( "move-assigning" ) {
			moved = std::move(original);

			THEN( "the moved-to object has valid state" ) {
				CHECK_FALSE( moved.IsValid() );
				CHECK( moved.GetPlanet() == nullptr );
				CHECK( moved.DisplayName() == "???" );
			}
		}
	}

	GIVEN( "a Wormhole instance for copy construction" ) {
		Wormhole original;

		WHEN( "copy-constructing" ) {
			Wormhole copy(original);

			THEN( "the copy has the same state as original" ) {
				CHECK( copy.IsValid() == original.IsValid() );
				CHECK( copy.GetPlanet() == original.GetPlanet() );
				CHECK( copy.DisplayName() == original.DisplayName() );
				CHECK( copy.IsMappable() == original.IsMappable() );
				CHECK( copy.IsAutogenerated() == original.IsAutogenerated() );
				CHECK( copy.Links().size() == original.Links().size() );
			}
		}
	}

	GIVEN( "a Wormhole instance for move construction" ) {
		Wormhole original;

		WHEN( "move-constructing" ) {
			Wormhole moved(std::move(original));

			THEN( "the moved instance has valid state" ) {
				CHECK_FALSE( moved.IsValid() );
				CHECK( moved.GetPlanet() == nullptr );
				CHECK( moved.DisplayName() == "???" );
				CHECK_FALSE( moved.IsMappable() );
				CHECK_FALSE( moved.IsAutogenerated() );
			}
		}
	}
}

// ============================================================================
// Integration Test Notes
// ============================================================================
// The following Wormhole functionality requires integration tests with full
// GameData initialization:
//
// 1. Load() method:
//    - Requires DataNode with properly formatted wormhole data
//    - Requires GameData::Systems() to resolve system names
//    - Requires GameData::Colors() to resolve color names
//    - Tests: loading "link" attributes, "mappable", "display name", "color"
//    - Tests: "add" and "remove" operations on links
//    - Tests: clearing links with "remove link"
//
// 2. LoadFromPlanet() method:
//    - Requires a valid Planet with proper Systems() setup
//    - Requires each System to have FindStellar() working
//    - Tests: automatic link generation between systems
//    - Tests: mappable flag based on planet description
//    - Tests: isAutogenerated flag is set to true
//
// 3. GenerateLinks() (private, called by LoadFromPlanet):
//    - Creates links forming a closed loop through all systems
//    - Handles one-way wormholes (when stellar object has no sprite)
//
// 4. WormholeSource() and WormholeDestination():
//    - Require valid System pointers in the links map
//    - Test: finding source/destination when links exist
//    - Test: returning input system when no link found
//
// 5. IsValid() with valid data:
//    - Test: returns true when all components are valid
//    - Test: returns false when planet is invalid
//    - Test: returns false when any linked system is invalid
//
// 6. SetPlanet():
//    - Test: with a valid Planet reference
// ============================================================================

// #endregion unit tests



} // test namespace