/* Locale.cpp
Copyright (c) 2024 by ES Translator Contributors

Endless Sky is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

Endless Sky is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include "Locale.h"

#include "Files.h"

#include <fstream>
#include <sstream>

// Platform-specific headers for language detection.
#ifdef _WIN32
#include <windows.h>
#elif defined(__APPLE__)
#include <CoreFoundation/CoreFoundation.h>
#else
#include <clocale>
#endif

using namespace std;



// Static member initialization.
string Locale::language = "en";
map<string, string> Locale::translations;



// Initialize the locale system with the specified language code.
void Locale::Init(const string &lang)
{
	language = lang;
	translations.clear();

	// Don't load translations for English (default).
	if(language == "en")
		return;

	// Construct path to translation file: locales/<language>.json
	filesystem::path localePath = Files::Resources() / "locales" / (language + ".json");

	if(!Files::Exists(localePath))
		return;

	LoadTranslations(localePath.string());
}



// Get a translated string by its key.
string Locale::Get(const string &key)
{
	auto it = translations.find(key);
	if(it != translations.end())
		return it->second;

	// Return the key itself if no translation found.
	return key;
}



// Check if a translation exists for the given key.
bool Locale::Has(const string &key)
{
	return translations.find(key) != translations.end();
}



// Format a translated string with variable substitutions.
string Locale::Format(const string &key, const map<string, string> &vars)
{
	string text = Get(key);

	// Replace {variable} placeholders with values.
	for(const auto &pair : vars)
	{
		string placeholder = "{" + pair.first + "}";
		size_t pos = 0;
		while((pos = text.find(placeholder, pos)) != string::npos)
		{
			text.replace(pos, placeholder.length(), pair.second);
			pos += pair.second.length();
		}
	}

	return text;
}



// Get the current language code.
const string &Locale::Language()
{
	return language;
}



// Clear all loaded translations.
void Locale::Clear()
{
	translations.clear();
	language = "en";
}



// Load translations from a JSON file.
void Locale::LoadTranslations(const string &path)
{
	string content = Files::Read(path);
	if(content.empty())
		return;

	// Simple JSON parser for nested objects.
	// This is a minimal implementation that handles the specific format
	// generated by es-translator: {"category": {"key": "value"}}

	size_t pos = 0;
	string currentCategory;

	while(pos < content.length())
	{
		// Skip whitespace.
		while(pos < content.length() && isspace(content[pos]))
			++pos;

		if(pos >= content.length())
			break;

		// Look for category name (top-level key).
		if(content[pos] == '"')
		{
			++pos;
			size_t start = pos;
			while(pos < content.length() && content[pos] != '"')
				++pos;

			string key = content.substr(start, pos - start);
			++pos;

			// Skip to the colon and opening brace.
			while(pos < content.length() && content[pos] != '{')
				++pos;

			if(pos >= content.length())
				break;

			++pos; // Skip '{'

			// Check if this is a nested object (category).
			size_t nextQuote = content.find('"', pos);
			size_t nextBrace = content.find('{', pos);

			if(nextQuote != string::npos && (nextBrace == string::npos || nextQuote < nextBrace))
			{
				// This is a category with nested keys.
				currentCategory = key;

				// Parse nested key-value pairs.
				while(pos < content.length())
				{
					// Skip whitespace.
					while(pos < content.length() && isspace(content[pos]))
						++pos;

					if(pos >= content.length() || content[pos] == '}')
						break;

					// Parse key.
					if(content[pos] == '"')
					{
						++pos;
						size_t keyStart = pos;
						while(pos < content.length() && content[pos] != '"')
							++pos;

						string nestedKey = content.substr(keyStart, pos - keyStart);
						++pos;

						// Skip to colon.
						while(pos < content.length() && content[pos] != ':')
							++pos;
						++pos;

						// Skip whitespace.
						while(pos < content.length() && isspace(content[pos]))
							++pos;

						// Parse value.
						if(content[pos] == '"')
						{
							++pos;
							size_t valueStart = pos;
							while(pos < content.length() && content[pos] != '"')
							{
								// Handle escaped quotes.
								if(content[pos] == '\\' && pos + 1 < content.length())
									++pos;
								++pos;
							}

							string value = content.substr(valueStart, pos - valueStart);
							++pos;

							// Store translation with dot notation.
							string fullKey = currentCategory + "." + nestedKey;
							translations[fullKey] = value;
						}
					}

					// Skip to next entry or closing brace.
					while(pos < content.length() && content[pos] != ',' && content[pos] != '}')
						++pos;

					if(pos < content.length() && content[pos] == ',')
						++pos;
				}
			}
		}

		++pos;
	}
}



// Detect system language and return the best matching language code.
string Locale::DetectSystemLanguage()
{
	string detectedLang = "en";

#ifdef _WIN32
	// Windows: Use GetUserDefaultUILanguage
	LANGID langId = GetUserDefaultUILanguage();
	char localeName[LOCALE_NAME_MAX_LENGTH];
	if(LCIDToLocaleName(MAKELCID(langId, SORT_DEFAULT), localeName, LOCALE_NAME_MAX_LENGTH, 0))
	{
		detectedLang = string(localeName);
		// Convert to lowercase
		for(char &c : detectedLang)
			c = static_cast<char>(tolower(static_cast<unsigned char>(c)));
		// Replace hyphen with underscore for consistency
		size_t hyphenPos = detectedLang.find('-');
		if(hyphenPos != string::npos)
			detectedLang.replace(hyphenPos, 1, "_");
	}
#elif defined(__APPLE__)
	// macOS: Use CFLocaleCopyCurrent
	CFLocaleRef locale = CFLocaleCopyCurrent();
	CFStringRef langCode = (CFStringRef)CFLocaleGetValue(locale, kCFLocaleLanguageCode);
	CFStringRef countryCode = (CFStringRef)CFLocaleGetValue(locale, kCFLocaleCountryCode);

	char langBuf[16] = {0};
	char countryBuf[16] = {0};

	CFStringGetCString(langCode, langBuf, sizeof(langBuf), kCFStringEncodingUTF8);
	if(countryCode)
		CFStringGetCString(countryCode, countryBuf, sizeof(countryBuf), kCFStringEncodingUTF8);

	if(countryBuf[0])
		detectedLang = string(langBuf) + "_" + string(countryBuf);
	else
		detectedLang = string(langBuf);

	CFRelease(locale);
#else
	// Linux/Unix: Use setlocale
	const char *locale = setlocale(LC_ALL, "");
	if(locale && locale[0] != '\0')
	{
		string localeStr(locale);
		// Extract language and country from locale string (e.g., "zh_CN.UTF-8" -> "zh_CN")
		size_t dotPos = localeStr.find('.');
		if(dotPos != string::npos)
			localeStr = localeStr.substr(0, dotPos);

		size_t atPos = localeStr.find('@');
		if(atPos != string::npos)
			localeStr = localeStr.substr(0, atPos);

		// Check for underscore separator
		size_t underscorePos = localeStr.find('_');
		if(underscorePos != string::npos)
		{
			string lang = localeStr.substr(0, underscorePos);
			string country = localeStr.substr(underscorePos + 1);
			// Convert to lowercase for consistency
			for(char &c : lang)
				c = static_cast<char>(tolower(static_cast<unsigned char>(c)));
			for(char &c : country)
				c = static_cast<char>(toupper(static_cast<unsigned char>(c)));
			detectedLang = lang + "_" + country;
		}
		else
		{
			// No country code, just language
			for(char &c : localeStr)
				c = static_cast<char>(tolower(static_cast<unsigned char>(c)));
			detectedLang = localeStr;
		}
	}
#endif

	// Map common language codes to supported formats
	// Chinese variants
	if(detectedLang == "zh_CN" || detectedLang == "zh_cn" || detectedLang == "zh_hans" || detectedLang == "zh_sg")
		return "zh_CN";
	if(detectedLang == "zh_TW" || detectedLang == "zh_tw" || detectedLang == "zh_hant" || detectedLang == "zh_hk" || detectedLang == "zh_mo")
		return "zh_TW";

	// Normalize to lowercase for single-language codes
	for(char &c : detectedLang)
		c = static_cast<char>(tolower(static_cast<unsigned char>(c)));

	// Check for supported languages
	if(detectedLang == "en" || detectedLang == "de" || detectedLang == "fr" ||
	   detectedLang == "es" || detectedLang == "it" || detectedLang == "ja" ||
	   detectedLang == "ko" || detectedLang == "pt" || detectedLang == "ru" ||
	   detectedLang == "zh_cn" || detectedLang == "zh_tw")
		return detectedLang;

	// Default to English if language not supported
	return "en";
}
