/* Locale.cpp
Copyright (c) 2024 by ES Translator Contributors

Endless Sky is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

Endless Sky is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include "Locale.h"

#include "Files.h"

#include <fstream>
#include <sstream>

using namespace std;



// Static member initialization.
string Locale::language = "en";
map<string, string> Locale::translations;



// Initialize the locale system with the specified language code.
void Locale::Init(const string &lang)
{
	language = lang;
	translations.clear();

	// Don't load translations for English (default).
	if(language == "en")
		return;

	// Construct path to translation file: locales/<language>.json
	filesystem::path localePath = Files::Resources() / "locales" / (language + ".json");

	if(!Files::Exists(localePath))
		return;

	LoadTranslations(localePath.string());
}



// Get a translated string by its key.
string Locale::Get(const string &key)
{
	auto it = translations.find(key);
	if(it != translations.end())
		return it->second;

	// Return the key itself if no translation found.
	return key;
}



// Check if a translation exists for the given key.
bool Locale::Has(const string &key)
{
	return translations.find(key) != translations.end();
}



// Format a translated string with variable substitutions.
string Locale::Format(const string &key, const map<string, string> &vars)
{
	string text = Get(key);

	// Replace {variable} placeholders with values.
	for(const auto &pair : vars)
	{
		string placeholder = "{" + pair.first + "}";
		size_t pos = 0;
		while((pos = text.find(placeholder, pos)) != string::npos)
		{
			text.replace(pos, placeholder.length(), pair.second);
			pos += pair.second.length();
		}
	}

	return text;
}



// Get the current language code.
const string &Locale::Language()
{
	return language;
}



// Clear all loaded translations.
void Locale::Clear()
{
	translations.clear();
	language = "en";
}



// Load translations from a JSON file.
void Locale::LoadTranslations(const string &path)
{
	string content = Files::Read(path);
	if(content.empty())
		return;

	// Simple JSON parser for nested objects.
	// This is a minimal implementation that handles the specific format
	// generated by es-translator: {"category": {"key": "value"}}

	size_t pos = 0;
	string currentCategory;

	while(pos < content.length())
	{
		// Skip whitespace.
		while(pos < content.length() && isspace(content[pos]))
			++pos;

		if(pos >= content.length())
			break;

		// Look for category name (top-level key).
		if(content[pos] == '"')
		{
			++pos;
			size_t start = pos;
			while(pos < content.length() && content[pos] != '"')
				++pos;

			string key = content.substr(start, pos - start);
			++pos;

			// Skip to the colon and opening brace.
			while(pos < content.length() && content[pos] != '{')
				++pos;

			if(pos >= content.length())
				break;

			++pos; // Skip '{'

			// Check if this is a nested object (category).
			size_t nextQuote = content.find('"', pos);
			size_t nextBrace = content.find('{', pos);

			if(nextQuote != string::npos && (nextBrace == string::npos || nextQuote < nextBrace))
			{
				// This is a category with nested keys.
				currentCategory = key;

				// Parse nested key-value pairs.
				while(pos < content.length())
				{
					// Skip whitespace.
					while(pos < content.length() && isspace(content[pos]))
						++pos;

					if(pos >= content.length() || content[pos] == '}')
						break;

					// Parse key.
					if(content[pos] == '"')
					{
						++pos;
						size_t keyStart = pos;
						while(pos < content.length() && content[pos] != '"')
							++pos;

						string nestedKey = content.substr(keyStart, pos - keyStart);
						++pos;

						// Skip to colon.
						while(pos < content.length() && content[pos] != ':')
							++pos;
						++pos;

						// Skip whitespace.
						while(pos < content.length() && isspace(content[pos]))
							++pos;

						// Parse value.
						if(content[pos] == '"')
						{
							++pos;
							size_t valueStart = pos;
							while(pos < content.length() && content[pos] != '"')
							{
								// Handle escaped quotes.
								if(content[pos] == '\\' && pos + 1 < content.length())
									++pos;
								++pos;
							}

							string value = content.substr(valueStart, pos - valueStart);
							++pos;

							// Store translation with dot notation.
							string fullKey = currentCategory + "." + nestedKey;
							translations[fullKey] = value;
						}
					}

					// Skip to next entry or closing brace.
					while(pos < content.length() && content[pos] != ',' && content[pos] != '}')
						++pos;

					if(pos < content.length() && content[pos] == ',')
						++pos;
				}
			}
		}

		++pos;
	}
}
